const content = require('../data/content.json');
const BASE = 'https://marbellaboatcharter.com';
const PHONE = '+34 682 25 25 26';
const EMAIL = 'info@marbellaboatcharter.com';
const e = value => String(value ?? '').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));

function header() { return `<a class="skip-link" href="#main">Skip to content</a><header class="site-header level5-header"><div class="site-header__inner shell--wide"><a class="brand-mark" href="/"><span class="brand-mark__sign" aria-hidden="true">M</span><span>Marbella Boat Charter</span></a><nav class="nav"><a href="/fleet">Fleet</a><a href="/experiences">Experiences</a><a href="/destinations">Destinations</a><a href="/owners">Owners</a><a href="/contact">Contact</a></nav><div class="header-actions"><a class="header-contact" href="tel:+34682252526">${PHONE}</a><a class="btn" data-variant="primary" href="/contact">Plan a charter</a><button class="menu-toggle" type="button" aria-label="Open navigation" aria-expanded="false" data-menu-toggle>☰</button></div></div><nav class="mobile-nav shell--wide" data-mobile-nav data-open="false"><a href="/fleet">Fleet</a><a href="/experiences">Experiences</a><a href="/destinations">Destinations</a><a href="/owners">Owners</a><a href="/contact">Contact</a></nav></header>`; }
function footer() { return `<footer class="site-footer level5-footer"><div class="shell footer-top"><div><a class="brand-mark" href="/"><span class="brand-mark__sign" aria-hidden="true">M</span><span>Marbella Boat Charter</span></a><p class="footer-note">Private yacht charter, sailing, fishing and group programmes across Marbella, Puerto Banús and the Costa del Sol.</p></div><nav class="footer-nav"><strong>Explore</strong><a href="/fleet">Fleet</a><a href="/experiences">Experiences</a><a href="/destinations">Destinations</a><a href="/owners">Yacht owners</a></nav><div class="footer-contact"><strong>Charter desk</strong><a href="tel:+34682252526">${PHONE}</a><a href="mailto:${EMAIL}">${EMAIL}</a><a href="/booking-terms">Booking terms</a></div></div><div class="shell footer-bottom"><span>© <span data-year></span> Marbella Boat Charter</span><span><a href="/privacy">Privacy</a> · <a href="/cookies">Cookies</a> · <a href="/legal">Legal</a></span></div></footer>`; }

module.exports = function handler(req,res) {
  const rawType=String(req.query.type||'');
  const type=rawType === 'destination' ? 'destinations' : rawType === 'experience' ? 'experiences' : rawType === 'service' ? 'services' : '';
  const slug=String(req.query.slug||'').toLowerCase().replace(/[^a-z0-9-]/g,'');
  const item=type && content[type] && content[type].find(x=>x.slug===slug);
  if (!item) return res.status(404).send('<!doctype html><title>Page not found</title><p>Page not found.</p>');
  const singular = type.slice(0,-1);
  const canonical=`${BASE}/${type}/${item.slug}`;
  const meta = type==='destinations' ? `Private yacht charter planning for ${item.title} with Marbella Boat Charter. Suitable vessels, route logic and current availability across the Costa del Sol.` : type==='experiences' ? `${item.title} in Marbella and Puerto Banús with professional crew and a curated charter fleet. Plan the correct vessel, duration and route.` : `${item.title} from Marbella Boat Charter in Marbella and Puerto Banús. Professional support from an experienced local yacht-charter and management team.`;
  let sections=[];
  if (type==='destinations') sections=[['Why this area',`What ${item.title} adds to the day.`,item.best],['Charter planning','Build the route around sea time, not road geography.',`${item.title} is treated as a charter area, not a promise that every vessel can board in every marina. Departure point, delivery, weather, route time and any extra mooring or fuel are confirmed for the chosen yacht.`],['Local expertise','Use the coast intelligently.','The charter team plans around the Costa del Sol, vessel range and current conditions so the itinerary is realistic for the booked duration.']];
  else if (type==='experiences') sections=[['Format','What the experience is really for.',item.intro],['Timing',`${item.duration} is the typical planning window.`,'The exact duration is matched to the vessel, weather, departure point and route. Longer-distance programmes need enough time on passage and should not be compressed into a short charter.'],['Vessel selection',`Best matched to ${item.vessels}.`,'The charter desk narrows the fleet based on guest count, onboard priorities, route, budget and the level of space or performance the day requires.']];
  else sections=[['Service',item.title,item.intro],['Scope','What can be coordinated.',item.items.join(' · ')],['Approach','One accountable point of contact.','The value is coordinating the details around the vessel or charter instead of forcing the client or owner to manage several disconnected suppliers.']];
  const schema={'@context':'https://schema.org','@graph':[{'@type':'Service','name':item.title,'description':meta,'provider':{'@type':'LocalBusiness','name':'Marbella Boat Charter','telephone':PHONE,'email':EMAIL},'areaServed':['Marbella','Puerto Banús','Costa del Sol'],'url':canonical},{'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Home','item':BASE},{'@type':'ListItem','position':2,'name':type[0].toUpperCase()+type.slice(1),'item':`${BASE}/${type}`},{'@type':'ListItem','position':3,'name':item.title,'item':canonical}]}]};
  const sectionHtml=sections.map(([kick,title,copy])=>`<section class="section shell"><div class="detail-grid"><div><p class="eyebrow">${e(kick)}</p><h2 class="display display--section">${e(title)}</h2></div><div class="panel"><p class="lead">${e(copy)}</p></div></div></section>`).join('');
  const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${e(item.title)} | Marbella Boat Charter</title><meta name="description" content="${e(meta)}"><link rel="canonical" href="${canonical}"><meta name="theme-color" content="#10131a"><link rel="stylesheet" href="/styles/brand.css"><link rel="stylesheet" href="/styles/site.css"><link rel="stylesheet" href="/styles/platform.css"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script></head><body>${header()}<main id="main"><section class="editorial-hero"><div class="shell editorial-hero__inner"><p class="eyebrow">${e(singular)}</p><h1 class="display display--xl">${e(item.title)}</h1><p class="lead">${e(item.intro)}</p><div class="hero__actions"><a class="btn" data-variant="primary" href="/contact?plan=${encodeURIComponent(item.slug)}">Plan this with the charter desk</a></div></div></section>${sectionHtml}<section class="section shell"><div class="panel panel--dark"><p class="eyebrow">Plan it properly</p><h2 class="display display--section">Availability, vessel and conditions are confirmed for the exact date.</h2><p class="lead">Tell the team the date, group size and what matters most. They will recommend the correct vessel and build the final quotation around the programme.</p><div class="hero__actions"><a class="btn" data-variant="ghost" href="/contact?plan=${encodeURIComponent(item.slug)}">Request a plan</a></div></div></section></main>${footer()}<script type="module" src="/scripts/site.js"></script><script type="module" src="/scripts/footer.js"></script><script type="module" src="/scripts/platform.js"></script></body></html>`;
  res.setHeader('Content-Type','text/html; charset=utf-8');
  res.setHeader('Cache-Control','public, max-age=0, s-maxage=3600, stale-while-revalidate=86400');
  return res.status(200).send(html);
};
